<?php

namespace AppBundle\Repository;

/**
 * CorreoElectronicoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CorreoElectronicoRepository extends \Doctrine\ORM\EntityRepository
{
}
