<?php

namespace AppBundle\Repository;

/**
 * DireccionPostalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DireccionPostalRepository extends \Doctrine\ORM\EntityRepository
{
}
