<?php

namespace AppBundle\Repository;

/**
 * ProfesionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfesionRepository extends \Doctrine\ORM\EntityRepository
{
}
