<?php

namespace AppBundle\Repository;

/**
 * ProfesionalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfesionalRepository extends \Doctrine\ORM\EntityRepository
{
}
