<?php

namespace AppBundle\Repository;

/**
 * TelefonoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TelefonoRepository extends \Doctrine\ORM\EntityRepository
{
}
